# Copyright 2019 Manna Harbour
# https://github.com/manna-harbour/miryoku

MIRYOKU_CLIPBOARD = WIN
MIRYOKU_ALPHAS = QWERTY
MIRYOKU_LANGUAGE = RU
OLED_ENABLE = yes
WPM_ENABLE = yes
SPLIT_WPM_ENABLE = yes
SPLIT_OLED_ENABLE = yes
SPLIT_MODS_ENABLE = yes
SPLIT_LAYER_STATE_ENABLE = yes
SPLIT_WATCHDOG_ENABLE = yes
UNICODE_ENABLE = yes
COMBO_ENABLE = yes
